project_id = "jimfuknlntcqgtqfwcod"

[functions.ai-autocomplete]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.evaluate-draft]
verify_jwt = true

[functions.evaluate-block]
verify_jwt = true

[functions.generate-sections]
verify_jwt = true

[functions.import-document]
verify_jwt = true

[functions.convert-html-to-blocks]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-collaboration-invite]
verify_jwt = true

[functions.send-newsletter]
verify_jwt = true

[functions.generate-blog]
verify_jwt = false

[functions.import-past-papers]
verify_jwt = false

[functions.import-subject-guides]
verify_jwt = false

[functions.import-r2-papers]
verify_jwt = false

[functions.upload-past-papers]
verify_jwt = false

[functions.sync-public-papers]
verify_jwt = false

[functions.sync-directory-papers]
verify_jwt = false

[functions.index-paper-uploads]
verify_jwt = false

[functions.manipulate-question]
verify_jwt = false
